### ISSUE TITLE
Server crash on connect with firefox.

### ISSUE THREAD

**Issue by AlexKraak** [NalaGinrut/artanis#44] opened 2015-10-09 19:20 UTC
Hello.
I run into the following error when I connect to the server with firefox:
 `ice-9/boot-9.scm:106:20: In procedure #<procedure 1f81cc0 at ice-9/boot-9.scm:97:6 (thrown-k . args)>:
ice-9/boot-9.scm:106:20: Bad qstring header component: 7q3qts
`
The error does not occur if i connect via curl or qupzilla. My firefox has had quite a few about:config settings changed so that may have something to do with it.

**Comment by NalaGinrut** [comment] 2015-10-10 03:21
What's your version of Guile?

And could you paste the complete error message thrown in server side?

**Comment by NalaGinrut** [comment] 2015-10-10 03:29
Anyway, this looks like the string 7q3qts wasn't surrounded with double-quote. According to  http://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html, quoted-string should be surrounded with double-quotes. So it's failed to pass the invalidation of Guile HTTP parser.

Here's a link could be helpful:
https://lists.gnu.org/archive/html/bug-guix/2014-12/msg00055.html

So could you paste the complete request header from the browser too? Thanks!

**Comment by AlexKraak** [comment] 2015-10-10 08:38
This is the server error message: 
`Anytime you want to Quit just try Ctrl+C, thanks!
http://0.0.0.0:8080
ice-9/boot-9.scm:106:20: In procedure #<procedure 2294780 at ice-9/boot-9.scm:97:6 (thrown-k . args)>:
ice-9/boot-9.scm:106:20: Bad qstring header component: tc11ztp


Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.`

I am running Guile 2.0.11.

How do i get the request header from the browser?

**Comment by NalaGinrut** [comment] 2015-10-10 08:41
Alright, it seems thrown in the very beginning so there's few information.

You may get request header easily if you use "Net" function in firebug if you use Firefox

**Comment by AlexKraak** [comment] 2015-10-10 08:47
The request is: 
`Accept	
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding	
gzip, deflate
Accept-Language	
en-US,en;q=0.5
Cache-Control	
max-age=0
Connection	
keep-alive
DNT	
1
Host	
0.0.0.0:8080
If-None-Match	
f4tdbga2x
User-Agent	
Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0
Via	
1.1 88.122.154.208
X-Forwarded-For	
49.189.154.166`

And the status is 400 Bad Request

**Comment by NalaGinrut** [comment] 2015-10-10 08:53
I think the problem is that
```
If-None-Match: f4tdbga2x
```
Should be
```
If-None-Match: "f4tdbga2x"
```
Or it breaks the rule of RFC2616.
Dunno why it didn't surrounded with double-quote, maybe it's a bug of Firefox?

**Comment by NalaGinrut** [comment] 2015-11-02 04:10
@AlexKraak I'll close this issue, feel free to reopen if you find new information.

**Closed by NalaGinrut** 2015-11-02 04:10 UTC
